title: "Ryan Z. Friedman"
description: My personal website.

theme: minima
show_excerpts: True

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

twitter_username: rfriedman22
github_username: rfriedman22
linkedin_username: ryanfriedman22
orcid_username: 0000-0001-9013-8676
google_scholar_username: TR8GZ_cAAAAJ
