title: "Ryan Z. Friedman"
description: My personal website.

theme: minima

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

minima:
  social_links:
    twitter: rfriedman22
    github: rfriedman22
    linkedin: rfriedman22
